### ISSUE TITLE
[ERROR]: Error during extraction: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by Utopiah** [AScriver/MHTMLExtractor#2]
Trying to unpack the result of `yt-dlp`. Getting as error : 

```
abien@fabien-CORSAIR-ONE-i160:~$ python MHTMLExtractor.py M*mhtml
[18:42:59][MHTMLExtractor.py:345][ERROR]: Error during extraction: 'utf-8' codec can't decode byte 0xff in position 3778: invalid start byte
```

**Comment by AScriver** [comment]
@Utopiah Are you able to provide the MHTML that you're trying to extract? I'm unfortunately not seeing how to get yt-dlp to output as MHTML.

**Comment by Utopiah** [comment]
Here it is https://fabien.benetou.fr/pub/home/test.mhtml let me know when I can delete it from my server.

yt-dlp should not, IMHO, output MHTML but only the video within it, but thought it was interesting to tinker with the format and thus tried your tool

**Comment by AScriver** [comment]
Thank you! I'll try to take a look at this today!

**Comment by AScriver** [comment]
@Utopiah Would you be able to give me the process that was used to get this output from yt-dlp? 

The raw JPEG data in the mhtml file seems to be slightly different than what I'm seeing returned from the Content-location headers. Since a lot of the bytes between these files are the same, I'm thinking some sort of compression happened in the process. I'm honestly not too familiar with what to look for to confirm this, so that's just a shot in the dark. 

As an example, the first few bytes of data returned from the [Content-location link](https://assets.webservices.francetelevisions.fr/v1/assets/sprites/202407/65cb58060754f/0313cc8d-439a-49d2-b512-1421e47c1799-65cb58060754f8.jpeg) are:
 `ÿØÿà JFIF` 
while the first few bytes of data belonging to the same image in the mhtml (line 88272):
`���� JFIF`

I'll continue to look into this, but I think being able to replicate the output from yt-dlp on my end would help.

**Comment by Utopiah** [comment]
Thanks for investigating. Unfortunately I can't remember which page I tried to get back then. I know that I was expecting a .mp4 in fact and that's what lead me to learn a bit about `mhtml` and your project. I just checked my `history` and it does not go back far enough to get the command with the right source.
